### ISSUE TITLE
Got Error when running kNN-MT with T5-base

### ISSUE THREAD

**Issue by vhientran** [neulab/knn-transformers#10]
Hi @urialon ,

Thanks for releasing your interesting source code. Following your guidance, I have tried to run [kNN-MT](https://github.com/neulab/knn-transformers/#machine-translation-knn-mt) when to evaluate the T5-base model.
Here is the [error image](https://shorturl.at/ilw08). The error is about "OverflowError: out of range integral type conversion attempted". I tried to increase the max_target_length (from 128 to 512, 1024) but still got error.
What should I do to fix it? Thank you for your help!

**Comment by vhientran** [comment]
I fixed it by replacing the token id (-100) to the padding token id (0). Thanks!

**Comment by urialon** [comment]
Thanks for letting me know, 
I'm happy to hear that you managed to get it to work!
