### ISSUE TITLE
NonMatchingSplitsSizesError

### ISSUE THREAD

**Issue by Jing-L97** [neulab/knn-transformers#12]
Hi, I encountered _NonMatchingSplitsSizesError_ when evaluating the finetuned model: gpt2-finetuned-wikitext103. The same also popped up when Saving a Datastore and  Building the FAISS index by myself. Would you mind indicating how to solve this issue? Thank you very much!

![image](https://github.com/neulab/knn-transformers/assets/84009338/ecf75a88-62d1-411d-bd9e-261298b3d048)

**Comment by urialon** [comment]
Hi @Jing-L97 ,
Thank you for your interest in our work.

Can you please provide your huggingface transformers version, the exact command line that you ran, the full stack trace, and whether you made any changes to the code?

Best,
Uri

**Comment by Jing-L97** [comment]
Hi Uri,

Thank you so much for your quick reply! 

I didn't make any change to the code. The transformers version is **4.28.1** and torch **2.1.0.** I downloaded gpt2-finetuned-wikitext103 and the command line is below.

MODEL=neulab/gpt2-finetuned-wikitext103
python -u run_clm.py \
  --model_name_or_path ${MODEL} \
  --dataset_name wikitext --dataset_config_name wikitext-103-raw-v1 \
  --output_dir checkpoints/${MODEL} \
  --do_eval --eval_subset validation

I was wondering if it's ok to set **ignore_verifications=True** when loading the dataset? I tried this but it returned another error (see attachment) when evaluating model using the code above. 

Thanks again for your kind help!

![image](https://github.com/neulab/knn-transformers/assets/84009338/927ddbf5-95b4-4940-bde8-e8845d2ecb3f)

![image](https://github.com/neulab/knn-transformers/assets/84009338/0237417e-c523-4206-9eba-0649cb931f6c)

![image](https://github.com/neulab/knn-transformers/assets/84009338/167be47a-ec51-403d-b742-8b09d050394b)

**Comment by urialon** [comment]
So what exactly is the problem?

**Comment by Jing-L97** [comment]
It returned error when evaluating the pretrained LM. 
1) If there is no change to the script, it returns the _NonMatchingSplitsSizesError_

2) If I add  _ignore_verifications=True_  to the loading_dataset, it returns another error, _servicetimeout_

And here's the commandline:
MODEL=neulab/gpt2-finetuned-wikitext103
python -u run_clm.py
--model_name_or_path ${MODEL}
--dataset_name wikitext --dataset_config_name wikitext-103-raw-v1
--output_dir checkpoints/${MODEL}
--do_eval --eval_subset validation

**Comment by Jing-L97** [comment]
Hi! I have successfully solved the issue by reinstalling the required packages. Thank you very much!

**Comment by urialon** [comment]
Great to hear!
