### ISSUE TITLE
Unsupported operand type(s) in LM evaluation

### ISSUE THREAD

**Issue by Jing-L97** [neulab/knn-transformers#13]
Hi, can I ask a question regarding the evaluating kNN-LM and RetoMaton? I used the preprocessed Wikitext-103 datastores and FAISS index from gpt-2 and distilgpt-2(downloading form the link) and encountered the 'unsupported operand type(s)' issue for both conditions. Would you mind indicating some possible solutions? 

Thank you very much for your kind help! 

<img width="1512" alt="Screenshot 2024-03-30 at 20 39 32" src="https://github.com/neulab/knn-transformers/assets/84009338/40e4e7ba-da6a-4f70-9eb1-96c0b10ac8db">

**Comment by urialon** [comment]
Can you list the content of the directory checkpoints/$MODEL ?

**Comment by Jing-L97** [comment]
Thank you very much for the quick reply! Here it is:

<img width="1508" alt="Screenshot 2024-03-30 at 21 24 18" src="https://github.com/neulab/knn-transformers/assets/84009338/2ad0ee6c-8909-4232-91f0-14cc15f5e9be">

**Comment by urialon** [comment]
The model name directory needs to be directly under `checkpoints`, without a `neulab` directory between them.

**Comment by Jing-L97** [comment]
Thank you very much! I put the model directory under checkpoints but it returns another issue: OSError: distilgpt2-finetuned-wikitext103 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

<img width="1508" alt="Screenshot 2024-03-30 at 21 46 08" src="https://github.com/neulab/knn-transformers/assets/84009338/7e978cfa-95b1-4786-a2fa-4c8540ba3f51">

**Comment by urialon** [comment]
The model path is incorrect

**Comment by Jing-L97** [comment]
Sorry I'm still very confused about model path. So I changed into this but it returned the same error as the very beginning. Thank you very much for your kind help!

<img width="1508" alt="Screenshot 2024-03-30 at 23 12 58" src="https://github.com/neulab/knn-transformers/assets/84009338/ba6ed83b-e4d0-4371-899c-01dcb0b94508">

**Comment by urialon** [comment]
This is a bit hard to debug remotely, but Please send your complete
directory structure, complete command line, error and stack trace, without
screenshots.

**Comment by Jing-L97** [comment]
Hi Uriaion, thank you so much for your kind help! Here's the directory structure

knn-transformers/
|-- CITATION.cff
|-- LICENSE
|-- README.md
|-- __pycache__
|   |-- knnlm.cpython-39.pyc
|   `-- retomaton.cpython-39.pyc
|-- checkpoints
|   |-- distilgpt2-finetuned-wikitext103
|   |   |-- all_results.json
|   |   |-- dstore_gpt2_None_768_keys.npy
|   |   |-- dstore_gpt2_None_768_vals.npy
|   |   |-- eval_results.json
|   |   `-- index_gpt2_None_768.indexed
|   |-- gpt2
|   |   |-- dstore_gpt2_116988150_768_vals.npy
|   |   |-- dstore_gpt2_None_768_vals.npy
|   |   |-- index_gpt2_116988150_768.indexed1
|   |   `-- index_gpt2_None_768.indexed
|   `-- neulab
|       |-- distilgpt2-finetuned-wikitext103
|       |   |-- all_results.json
|       |   |-- dstore_gpt2_None_768_keys.npy
|       |   |-- dstore_gpt2_None_768_vals.npy
|       |   |-- eval_results.json
|       |   `-- index_gpt2_None_768.indexed
|       `-- gpt2-finetuned-wikitext103
|           |-- all_results.json
|           |-- dstore_gpt2_None_768_keys.npy
|           |-- dstore_gpt2_None_768_vals.npy
|           |-- eval_results.json
|           `-- index_gpt2_None_768.indexed
|-- images
|   |-- overview.jpeg
|   |-- wiki.png
|   |-- wiki_distilgpt2.png
|   `-- wiki_gpt2.png
|-- knnlm.py
|-- load_model.py
|-- requirements.txt
|-- retomaton.py
|-- run_clm.py
`-- run_translation.py

**Comment by Jing-L97** [comment]
And here's the complete command line for retomaton evaluation and the datastore as well as index have been downloaded:

MODEL=neulab/distilgpt2-finetuned-wikitext103
python -u run_clm.py \
  --model_name_or_path ${MODEL} \
  --dataset_name wikitext --dataset_config_name wikitext-103-raw-v1 \
  --output_dir checkpoints/${MODEL} \
  --do_eval --eval_subset validation \
  --dstore_dir checkpoints/${MODEL} --retomaton

**Comment by Jing-L97** [comment]
And here's the error and stack trace after running the commands above. Thank you so much for your kind help!

03/30/2024 19:29:38 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 4distributed training: True, 16-bits training: False
/projectnb/tin-lab/jliu8/.conda/envs/RAG/lib/python3.9/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
03/30/2024 19:29:44 - WARNING - accelerate.utils.other - Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
03/30/2024 19:29:44 - INFO - retomaton - No member files found in checkpoints/neulab/distilgpt2-finetuned-wikitext103, not using clustering
03/30/2024 19:29:50 - INFO - knnlm - Reading datastore took 6.4537224769592285 s
03/30/2024 19:29:55 - INFO - knnlm - Moving index to GPU took 4.194196462631226 s



Traceback (most recent call last):
  File "/projectnb/tin-lab/jing/knn-transformers/run_clm.py", line 649, in <module>
    main()
  File "/projectnb/tin-lab/jing/knn-transformers/run_clm.py", line 589, in main
    knn_wrapper.break_into(model)
  File "/projectnb/tin-lab/jing/knn-transformers/knnlm.py", line 134, in break_into
    self.reconstruct_index, self.index = self.setup_faiss()
  File "/projectnb/tin-lab/jing/knn-transformers/knnlm.py", line 107, in setup_faiss
    self.vals = np.memmap(f'{keys_vals_prefix}_vals.npy', dtype=np.int32, mode='r',
  File "/projectnb/tin-lab/jliu8/.conda/envs/RAG/lib/python3.9/site-packages/numpy/core/memmap.py", line 249, in __new__
    size *= k
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by Jing-L97** [comment]
Hi ,I have solved this issue. It turns out that I didn't specify the datastore_size. It would be great if you could add the argument in **--dstore_size 116988150** in Step4 as well. Thank you very much for your kind help!

**Comment by urialon** [comment]
Thank you for catching this!
