### ISSUE TITLE
Performance on neulab/gpt2-large-finetuned-wikitext103

### ISSUE THREAD

**Issue by xszheng2020** [neulab/knn-transformers#4]
Hi, @urialon 
Thanks for your great work.
I just tested `neulab/gpt2-large-finetuned-wikitext103` without and with `--knn` but could not observe an improvement... 
ppl 10.5565 vs ppl 10.6538
Any idea about this? Should I tune the hyperparameters like temperature?
Thanks.

**Comment by urialon** [comment]
Hi @xszheng2020 ,
Thank you for your interest in our work and for your kind words!

Yes, in GPT2-large, a large temperature of **13** was needed.

In general, we noticed that KNN-based models tend to provide more benefit as the model is **smaller**:

![image](https://user-images.githubusercontent.com/15002544/188506189-59c3f39c-567e-4880-ae39-fecf8c396bf9.png)

Finding a way to make KNN-LM and RetoMaton be more useful in large models is a really interesting problem, or finding out an explanation as to why it behaves like that.

Best,
Uri

**Comment by xszheng2020** [comment]
Hi @urialon 
Thanks a lot!
I adjusted the temperature and got similar results as you pointed out (after I posted this issue), so I closed the issue directly!
Thanks again!
